### ISSUE TITLE
when I print logs, deadlock!

### ISSUE THREAD

**Issue by MrOnepiece** [onrik/logrus#17]
hi, i have some trouble.

i use like this: 
filenameHook := filename.NewHook()
filenameHook.Field = "custom_source_field"
log.AddHook(filenameHook)
log.Infof("finish init logger")

BUT, it happened:
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc000090034, 0x10c3300, 0x1)
        /usr/local/Cellar/go/1.13.3/libexec/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000090030)
        /usr/local/Cellar/go/1.13.3/libexec/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
        /usr/local/Cellar/go/1.13.3/libexec/src/sync/mutex.go:81
github.com/sirupsen/logrus.(*MutexWrap).Lock(...)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/logger.go:53
github.com/sirupsen/logrus.(*Entry).WithFields(0xc0000900e0, 0xc00007ca70, 0x0)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/entry.go:125 +0x68d
github.com/sirupsen/logrus.(*Entry).WithField(...)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/entry.go:120
github.com/onrik/logrus/filename.(*wrapper).Format(0xc00000c0a0, 0xc0000900e0, 0x30, 0x10d7420, 0xc00004d401, 0xc000074270, 0xc00007cc10)
        /Users/onepiece/go/src/github.com/onrik/logrus/filename/filename.go:19 +0x184
github.com/sirupsen/logrus.(*Entry).write(0xc0000900e0)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/entry.go:270 +0xa1
github.com/sirupsen/logrus.Entry.log(0xc000090000, 0xc000074240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/entry.go:246 +0x19d
github.com/sirupsen/logrus.(*Entry).Log(0xc000090070, 0x4, 0xc00007ce30, 0x1, 0x1)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/entry.go:282 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc000090070, 0xc000000004, 0x10eef3b, 0x11, 0xc00007cee0, 0x1, 0x1)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/entry.go:328 +0xe2
github.com/sirupsen/logrus.(*Logger).Logf(0xc000090000, 0x4, 0x10eef3b, 0x11, 0xc00007cee0, 0x1, 0x1)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/logger.go:146 +0x94
github.com/sirupsen/logrus.(*Logger).Infof(...)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/logger.go:160
github.com/sirupsen/logrus.Infof(...)
        /Users/onepiece/go/src/github.com/sirupsen/logrus/exported.go:154
main.initLogger(0x10ed49d, 0x4)
        /Users/onepiece/go/src/awesomeProject2/main.go:39 +0x1fb
main.main()
        /Users/onepiece/go/src/awesomeProject2/main.go:12 +0x3a
exit status 2

could someone help me? Thanks!!

**Comment by MrOnepiece** [comment]
when i rollback logrus version, it solved
